log:
  stdout: true
  level: info

persistence:
  defaultStore: default
  visibilityStore: visibility
  numHistoryShards: 1
  datastores:
    default:
      sql:
        pluginName: postgres12
        databaseName: temporal
        connectAddr: postgresql:5432
        connectProtocol: tcp
        user: temporal
        password: temporal
        maxConns: 20
        maxIdleConns: 20
        maxConnLifetime: 1h
    visibility:
      sql:
        pluginName: postgres12
        databaseName: temporal_visibility
        connectAddr: postgresql:5432
        connectProtocol: tcp
        user: temporal
        password: temporal
        maxConns: 10
        maxIdleConns: 10
        maxConnLifetime: 1h

global:
  membership:
    maxJoinDuration: 30s
    broadcastAddress: 0.0.0.0
  pprof:
    port: 0

  authorization:
    # Enable JWT claim mapper for OAuth/SSO integration
    claimMapper: "default"
    jwtKeyProvider:
      keySourceURIs:
        # Mock OAuth server JWKS endpoint
        - "http://oauth-mock:8080/.well-known/jwks.json"
      refreshInterval: 1h
    # Permissions mapping for JWT claims
    permissionsClaimName: "permissions"

  metrics:
    prometheus:
      timerType: histogram
      listenAddress: 0.0.0.0:9090

services:
  frontend:
    rpc:
      # (!) non-default ports to avoid conflict with internal-frontend
      grpcPort: 7232
      membershipPort: 6932
      bindOnLocalHost: false
      httpPort: 7242
  internal-frontend:
    rpc:
      grpcPort: 7233
      membershipPort: 6933
      bindOnLocalHost: false
      httpPort: 7243
  history:
    rpc:
      grpcPort: 7234
      membershipPort: 6934
      bindOnLocalHost: false
  matching:
    rpc:
      grpcPort: 7235
      membershipPort: 6935
      bindOnLocalHost: false
  worker:
    rpc:
      grpcPort: 7239
      membershipPort: 6939
      bindOnLocalHost: false

clusterMetadata:
  enableGlobalNamespace: false
  failoverVersionIncrement: 10
  masterClusterName: "active"
  currentClusterName: "active"
  clusterInformation:
    active:
      enabled: true
      initialFailoverVersion: 1
      rpcName: "frontend"
      rpcAddress: "temporal-frontend-internal:7233"

dcRedirectionPolicy:
  policy: "noop"
  toDC: ""
